// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqwtQjLelh5Btm7DSc26OjWmjuCcfh4rI',
    appId: '1:793982976631:web:249bcb8bbcfd4cb93d7c72',
    messagingSenderId: '793982976631',
    projectId: 'moovy-c44fa',
    authDomain: 'moovy-c44fa.firebaseapp.com',
    storageBucket: 'moovy-c44fa.firebasestorage.app',
    measurementId: 'G-ZT01GVFRHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn_7xbjz2Vg1kuWDae0345IwgDCK6L1SQ',
    appId: '1:793982976631:android:a5e0e61e508de9be3d7c72',
    messagingSenderId: '793982976631',
    projectId: 'moovy-c44fa',
    storageBucket: 'moovy-c44fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxgW6strhM_totBHwX8tZJyu0yFs4ukWg',
    appId: '1:793982976631:ios:8a8d965c4659015c3d7c72',
    messagingSenderId: '793982976631',
    projectId: 'moovy-c44fa',
    storageBucket: 'moovy-c44fa.firebasestorage.app',
    iosBundleId: 'com.cardosoit.moovy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxgW6strhM_totBHwX8tZJyu0yFs4ukWg',
    appId: '1:793982976631:ios:9623bf153791b08d3d7c72',
    messagingSenderId: '793982976631',
    projectId: 'moovy-c44fa',
    storageBucket: 'moovy-c44fa.firebasestorage.app',
    iosBundleId: 'com.cardosoit.moovy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqwtQjLelh5Btm7DSc26OjWmjuCcfh4rI',
    appId: '1:793982976631:web:c0f8abd3a0c554de3d7c72',
    messagingSenderId: '793982976631',
    projectId: 'moovy-c44fa',
    authDomain: 'moovy-c44fa.firebaseapp.com',
    storageBucket: 'moovy-c44fa.firebasestorage.app',
    measurementId: 'G-HG1RFHYT5F',
  );
}
